settings:
  prefix: "&8[&6&lA&e&lA&8] &r"
  logging: true
  prevent-logged-from-another-location: true
  default-lang: "en"
  actions:
    # default = Block action only for unauthenticated.
    # always  = Always block the action.
    # never   = Never block this action.
    deny-commands: default
    deny-chat: default
    deny-be-a-mob-target: default
    deny-block-break-place: default
    deny-damage: default
    deny-food-level-change: default
    deny-health-change: default
    deny-interact: default
    deny-inventory: default
    deny-item-pickup: default
    deny-move: default
    deny-projectiles: default
    deny-statistic-increment: default
    deny-vehicles: default
  teleport-spawn:
    enabled: false
    location:
      world: ""
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
storage: 
  # The storage container will be used to store the names and passwords of the registered accounts
  database:
    # URI format: 
    #     driver://address/database
    # with authentication: 
    #     driver://username:password@address/database
    #
    # Available drivers: MongoDB
    uri: "mongodb://localhost/minecraft"
    collection: "Users"
  # The cache buffer will be used for fast access data, such as sessions and synchronization
  cache:
    # Available drivers: memory, redis
    driver: "memory"
    expiration: 1440 # In minutes (1440 = 1 day)
    # The following values are only valid if no memory cache is used (memory selected)
    host: "localhost"
    port: 6379
    password: ""
authentication:
  kick: true
  max-accounts-per-ip: 1
  message-interval: 2
  timeout: 30
  resume-session-by-default: false
  send-server-on-login:
    enabled: false
    proxy: bungeecord
    servers:
      - lobby
security:
  country-check:
    enabled: false
    mode: blacklist
    list:
      - "cn"
      - "ru"
  cipher: "bcrypt"
  allowed-commands:
    - "/login"
    - "/l"
    - "/logout"
    - "/register"
    - "/reg"
  password-min-length: 6
  password-max-length: 32
  password-blacklist:
    - "1234"
    - "123456"
    - "654321"
    - "abcdef"
    - "fedcba"
    - "qwerty"
    - "minecraft"
    - "password"
    - "asdasd"
    - "asdfasdf"
    - "wasdwasd"